### PR TITLE
Initial commit of config file for MKS SBase

### PR DESCRIPTION
**Pull request by Bierfahrer**

### CODE REVIEW

**Comment by Fulg** [comment]
It seems you have enabled Z homing and disabled Z probing, how can this work?

**Comment by Bierfahrer** [comment]
It works like a charm.

I have set the Z offset with the M206 command:
M206 Z-1.50

saved to sd card with M500

The rest happens in my start gcode script. Something like:

M28 X0 Y0
G1 X145 Y140 F4000
M28 Z0
G1 Z0

I dont use bed leveling

**Comment by Fulg** [comment]
Ah, so your bed is reachable by the probe while XY is homed. This is the key :)

**Comment by Bierfahrer** [comment]
No, my bed is not reachable when iam "at home"  (X=0 and Y=0)

Thats why i do first the `G28 X0 Y0` to just home X and Y.

Then i center the printhead with `G1 X145 Y140 F4000` and afterwards home Z with `G28 Z0`

my whole start script:
`G91 				; relative movements
G1 Z5 F2500  		; lift nozzle
G90 				; back to absolute

G28 X0 Y0
G0 X140 Y140 F6000
G28 Z0 F30
G1 Z0

G91 				; relative movements
G1 Z5 F2500  		; lift nozzle
G90 				; back to absolute`

**Comment by Fulg** [comment]
Ah, I see. I ran like this for a while but found it too unsafe. If you ever send a naked `G28` to the printer, you will crash the head. This is also not recommended by Smoothie (a probe is not an endstop, even if you can get it to work like one).

In many interfaces there is a handy button to home the printer, better be quick on the power button if you click it by accident :)

**Pull request merged**
