### PR TITLE
Initializing Duet Wifi firmware directory

### PR DESCRIPTION
**Pull request by yonkiman**

### CODE REVIEW

**Comment by mzbotreprap** [comment]
It looks like all of your paths have your username in them. I don't mind you claiming credit, but it makes the folder structure a bit of a mess.

**Comment by yonkiman** [comment]
It actually wasn't about credit (don't care about that at all) but I thought it would be a good way to store multiple configs, which I thought would be good because:

- I might not have the best config, 
- I'd like to see other users' configs,
- Mine will be (eventually) optimized for the Y adapter dual filament solution.

Maybe instead of my username I could change it to "dual_extrusion_switching" or something?

What do you think?  I'll go with whatever you want.

**Comment by mzbotreprap** [comment]
That works. We'll tweak this as more of these come in.

**Comment by yonkiman** [comment]
Thanks Maks!

**Pull request merged**
