### PR TITLE
Added BOM in excel format

### PR DESCRIPTION
**Pull request by franknitty69**
BOM in excel format

### CODE REVIEW

**Comment by mzbotreprap** [comment]
Are you committing to keeping this updated from the MarkDown one?

**Comment by franknitty69** [comment]
sure thing. i'm very active on github and will make whatever changes necessary to keep it updated.

**Comment by nallar** [comment]
Do you want this because markdown tables are a massive pain to edit?

You can paste it into http://www.tablesgenerator.com/markdown_tables (file -> paste table data), edit it, then export back to markdown. Might help if that's why you want an excel version.

**Comment by franknitty69** [comment]
i can use markdown. i was only using excel due to the calculations.

**Comment by dcousens** [comment]
CSV displays pretty well on GitHub

**Pull request closed without merging**
